Ingesting Spectra for Manj19
SIMPLE-AstroDB/SIMPLE-db pull request #228
Opened 2021-12-12 00:08 UTC by SherelynA

2021-12-15 16:59 UTC, kelle commented
If you want, you can save just the Publications, Telescope, Instrument, Mode table with these commands: 
```
db.save_reference_table('Publications', 'data')   
db.save_reference_table('Telescopes', 'data')   
db.save_reference_table('Instruments', 'data')   
db.save_reference_table('Modes', 'data')   
```

And then commit and push the resulting changes to the four JSON files. 

After you do that, you can comment out the telescope and publication ingests calls.

2022-01-18 20:53 UTC, dr-rodriguez requested changes

2022-01-18 20:53 UTC, dr-rodriguez commented on simple/schema.py
> +    other_references = Column(String(30))
Also use `Column(String(100))` here

2022-01-18 20:53 UTC, dr-rodriguez commented on documentation/Spectra.md
> +| *other_references  | Other References |   | String(30) |   |
If you update the String size in the schema, update it here too

2022-01-25 20:15 UTC, dr-rodriguez approved these changes

2022-01-25 20:19 UTC, Will-Cooper approved these changes

2022-01-25 22:58 UTC, merged