Ingesting Spectra for Manj20
SIMPLE-AstroDB/SIMPLE-db pull request #239
Opened 2022-01-25 22:19 UTC by SherelynA

2022-02-08 21:50 UTC, SherelynA commented
Link to Google Sheet: https://docs.google.com/spreadsheets/d/1_RxjvPuPcNVswinf1q2zzM61plaP3Z9_b7UTRJCtFxk/edit?usp=sharing

2022-03-02 22:22 UTC, kelle requested changes

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11074656-7615174.json
> +            "reference": "G\u00f3me01",
needs to be fixed

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11085497–7632410.json
> +            "source": "2MASS J11085497\u20137632410",
\u needs to be fixed

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11085497–7632410.json
> +            "other_name": "2MASS J11085497\u20137632410"
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11123099–7653342.json
> +            "source": "2MASS J11123099\u20137653342",
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11123099–7653342.json
> +            "reference": "L\u00f3pe04",
fix

2022-03-02 22:22 UTC, kelle commented on data/2mass_j11123099–7653342.json
> +            "other_name": "2MASS J11123099\u20137653342"
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j15591135–2338002.json
> +            "source": "2MASS J15591135\u20132338002",
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j15591135–2338002.json
> +            "other_name": "2MASS J15591135\u20132338002"
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j16060391–2056443.json
> +            "source": "2MASS J16060391\u20132056443",
fix \u

2022-03-02 22:22 UTC, kelle commented on data/2mass_j16060391–2056443.json
> +            "other_name": "2MASS J16060391\u20132056443"
fix \u

2022-03-02 22:22 UTC, kelle commented on data/Publications.json
> +        "publication": "L\u00f3pe04",
fix

2022-03-02 22:22 UTC, kelle commented on data/Publications.json
> +        "publication": "G\u00f3me01",
fix

2022-03-02 22:22 UTC, kelle commented on data/usco_j160606.29-233513.3.json
> +            "other_name": "2MASS J16060629\u20132335133"
fix

2022-03-02 22:22 UTC, kelle commented on scripts/ingests/ingest_utils.py
> +            elif db.query(db.Publications).filter(db.Publications.c.name == references[i]).count() == 0:
```suggestion
            if db.query(db.Publications).filter(db.Publications.c.name == references[i]).count() == 0:
```

2022-03-02 22:22 UTC, kelle commented on scripts/ingests/ingest_utils.py
> +            elif db.query(db.Publications).filter(db.Publications.c.name == references[i]).count() == 0:
Also get rid of "TODO" on line 784

2022-03-04 20:22 UTC, kelle requested changes
two teeny things left -- so close!

2022-03-04 20:22 UTC, kelle commented on data/2mass_j15591135–2338002.json
> +            "source": "2MASS J15591135\u20132338002",
Looks like this one was missed by the most recent commit.

2022-03-04 20:22 UTC, kelle commented on scripts/ingests/ingest_utils.py
> +            if db.query(db.Publications).filter(db.Publications.c.name == references[i]).count() == 0:
This function looks great!  Delete line 866 that contains the TODO item.

2022-03-04 21:16 UTC, kelle approved these changes

2022-03-04 21:16 UTC, merged