Companions table
SIMPLE-AstroDB/SIMPLE-db pull request #385
Opened 2023-07-11 19:44 UTC by Ajb2307

2023-07-20 21:22 UTC, Ajb2307 commented
Note because there's no companion relationship schema this branch will fail

2023-07-22 00:19 UTC, kelle commented
Go ahead and commit your modifications to schema.py.  Your changes supersede what I started anyway.

2023-07-22 00:25 UTC, kelle commented
I added the documentation file here so I'll close my PR in favor of this one.

2023-07-22 00:34 UTC, kelle requested changes
The tests in `test_utils` should be setup differently using `pytest.raises` and not try/excepts.

2023-07-22 00:34 UTC, kelle commented on tests/test_utils.py
> +        pass
```suggestion
    with pytest.raises(SimpleError) as error_message:
        ingest_companion_relationship(db, 'Fake 1', None )
        assert 'some string' in str(error_message.value)
```

2023-07-26 19:44 UTC, dr-rodriguez commented on tests/test_integrity.py
>      db.engine.dispose()
The `test_remove_database` function deletes the database. There should be no tests after this.

2023-08-01 19:00 UTC, kelle approved these changes
LGTM!

2023-08-03 14:49 UTC, merged