code
SIMPLE-AstroDB/SIMPLE-db pull request #528
Opened 2024-07-01 19:48 UTC by Exu-112

Short description: Ingest of parallaxes from Ultracool sheet

Link to relevant issue: Closes #527 

For data ingests:
[ ] includes script used for ingest
[ ] includes modified JSON files
[ ] Add new tests
[ ] Update the Versions table

2024-07-01 20:03 UTC, kelle commented on simple/utils/astrometry.py
> +    logger.info(f" Photometry added to database: {parallax_data}\n")
Put into try/except
```Python
try:
            ...
            n_added += 1
            logger.info(f"Parallax added to database: \n " f"{parallax_data}")
        except sqlalchemy.exc.IntegrityError as e:
            msg = (
                "The source may not exist in Sources table.\n"
                "The parallax reference may not exist in Publications table. "
                "Add it with add_publication function. \n"
                "The parallax measurement may be a duplicate."
            )
            logger.error(msg)
            raise AstroDBError(msg) from e
```

2024-07-01 20:04 UTC, kelle commented on simple/utils/astrometry.py
> +):
Add docstring.

2024-07-01 20:05 UTC, kelle commented on simple/utils/astrometry.py
> +    comment: str = None,
add `raise_error` flag so user can decide if they want the script to fail or to keep going.
```python
if raise_error:
    raise
else:
    logger.warning
```

2024-07-01 20:55 UTC, kelle commented on tests/test_astrometry.py
> +        assert False, "ingest_parallax ingested bad source without exception"
```python
with pytest.raises(AstroDBError) as error_message:
        ingest_radial_velocity(
            temp_db, source="not a source", rv=12.5, rv_err=0.5, reference="Ref 1"
        )
    assert "No unique source match" in str(error_message.value)
```

2024-07-01 21:32 UTC, kelle commented on simple/utils/astrometry.py
> +def ingest_parallax(
You can go ahead and delete the old ingest_parallaxes function.

2024-07-02 19:53 UTC, kelle commented
return a dictionary called `flags`.  
- "added": True if it's added and False if it's skipped. 
- "content": the data that was attempted to add
- "message": string which includes information about why skipped

2024-07-03 02:27 UTC, Exu-112 commented
> return a dictionary called `flags`.
> 
> * "added": True if it's added and False if it's skipped.
> * "content": the data that was attempted to add
> * "message": string which includes information about why skipped

How should errors be handled? Should we return with the flags immediately or raise an error with the flags contained within? The first option would be a little confusing with regard to the raise_error flag and the fact that we don't raise errors anymore, but the second doesn't give you the flags dictionary anyways which seems to defeat the point of having it in the first place.

2024-07-03 03:16 UTC, kelle commented
When raise_error is True, you don't need to return anything. But when raise_error is False is when the flags are most important cause it should return added: False.

2024-07-03 16:58 UTC, kelle commented on simple/utils/astrometry.py
> +        reference for the parallax data
docstring should agree with keywords in the function

2024-07-08 16:04 UTC, kelle requested changes
Looking great but still some tweaking to do.

2024-07-08 16:04 UTC, kelle commented on simple/utils/astrometry.py
> +        raise error if there is an error during ingest
Be explicit
True: raises an error
False: does not raise an error, returns flags dictionary.

2024-07-08 16:04 UTC, kelle commented on simple/utils/astrometry.py
>      """
Add `Returns` part of docstring.

2024-07-08 16:04 UTC, kelle commented on scripts/ingests/ultracool_sheet/Ingest_Parallax.py
> +if DB_SAVE:
add a check which makes sure the counts add up to what you expect.

2024-07-08 16:57 UTC, kelle commented on scripts/ingests/ultracool_sheet/Ingest_Parallax.py
> +                reference = "Harr15"
delete.

2024-07-08 17:04 UTC, kelle commented on simple/utils/astrometry.py
> +        msg = ""
Just for readability  set `flags["added"] = False` here.

2024-07-08 17:05 UTC, kelle commented on tests/test_astrometry.py
> +    )
Duplicate these tests with `raise_error = False`.  In each scenario, test all three elements of the flags dictionary.

2024-07-08 17:56 UTC, kelle commented on simple/utils/astrometry.py
> +    raise_error: bool = True,
I think these should be keyword arguments.

2024-07-08 17:57 UTC, kelle commented on tests/test_astrometry.py
> +    print(flags)
delete.

2024-07-08 17:57 UTC, kelle commented on tests/test_astrometry.py
> +    print(flags)
delete.

2024-07-08 18:21 UTC, kelle commented on scripts/ingests/ultracool_sheet/Ingest_Parallax.py
> +            )
use the keywords.

2024-07-08 18:23 UTC, kelle commented on simple/utils/astrometry.py
> +        parallax uncertainty in arcseconds
Units are milliarcseconds

2024-07-08 18:23 UTC, kelle commented on simple/utils/astrometry.py
> +        parallax uncertainty in arcseconds
```suggestion
    parallax_mas: float
        parallax of source in arcseconds
    parallax_err_mas: float
        parallax uncertainty in arcseconds
```

2024-07-08 18:34 UTC, kelle approved these changes

2024-07-08 18:35 UTC, merged